name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

env:
  PIP_UPLOADED_PRIOR_TO: P7D

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      tracked-files: ${{ steps.filter.outputs.tracked-files }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Filter files
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 #v3.0.2
        id: filter
        with:
          filters: |
            tracked-files:
              - 'setup.py'
              - 'pyproject.toml'
              - '.conda/**'
              - 'src/**'

  verify-conda-build:
    name: Verify Conda Build
    runs-on: ubuntu-latest
    needs: changes
    # Only run if there are changes in the tracked files
    if: ${{ needs.changes.outputs.tracked-files == 'true' }}
    env:
      BUILD_FOLDER: ${{github.workspace}}/build
    steps:
      - uses: actions/checkout@v4

      - name: Set package path
        id: set-package-path
        run: |
          echo "package-path=${{env.BUILD_FOLDER}}/noarch/*${{vars.PACKAGE_FORMAT}}" >> $GITHUB_OUTPUT

      - name: Setup conda build environment
        uses: conda-incubator/setup-miniconda@a4260408e20b96e80095f42ff7f1a15b27dd94ca # v3.0.4
        with:
          miniconda-version: "latest"
          python-version: ${{ vars.PY_VERSION }} 
          environment-file: .conda/env_build.yml
          auto-activate-base: false
          auto-update-conda: false
          show-channel-urls: true

      - name: Verify conda recipe
        shell: bash -el {0}
        run: conda-verify .conda --ignore C2105,C2122
        # C2105: invalid package version for 'replace_landsurface' 
        # (there is no git tag in this test so versioneer outputs a 
        # version that conda-verify recognizes as 'invalid')
        # C2122: invalid license family
        # Reference --> https://github.com/conda/conda-verify?tab=readme-ov-file#checks

      - name: Build conda package
        shell: bash -el {0}
        run: conda build . --no-anaconda-upload --output-folder=${{env.BUILD_FOLDER}} -c accessnri -c conda-forge -c coecms --package-format ${{vars.PACKAGE_FORMAT}}

      - name: Verify conda package
        shell: bash -el {0}
        run: conda-verify ${{steps.set-package-path.outputs.package-path}} --ignore C1105,C1115,C1141
        # C1105: invalid version number for 'replace_landsurface' 
        # (there is no git tag in this test so versioneer outputs a 
        # version that conda-verify recognizes as 'invalid')
        # C1115: Found invalid license
        # C1141: Found python file without a corresponding pyc file
        # Reference --> https://github.com/conda/conda-verify?tab=readme-ov-file#checks
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          path: ${{steps.set-package-path.outputs.package-path}}
  
  get-deployment-sites:
    name: Get Deployment Sites
    runs-on: ubuntu-latest
    outputs:
      deployment-sites: ${{ steps.get-deployment-sites.outputs.deployment-sites }}
    steps:
      - name: Checkout config
        uses: actions/checkout@v4

      - name: Get sites
        id: get-deployment-sites
        run: |
            sites=$(jq --compact-output '.sites' ./.github/config/deployment-sites.json)
            echo "Found the following deployment sites: $sites"
            echo "deployment-sites=$sites" >> $GITHUB_OUTPUT
  
  testing:
    name: Run tests
    runs-on: ubuntu-latest
    needs: get-deployment-sites
    strategy:
      fail-fast: false
      matrix:
        deployment-site: ${{ fromJson(needs.get-deployment-sites.outputs.deployment-sites) }}
    environment: ${{ matrix.deployment-site }}
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: access-nri/actions/.github/actions/setup-ssh@main
        id: ssh
        with:
          hosts: |
            ${{ secrets.HOST_DATA }}
            ${{ secrets.HOST }}
          private-key: ${{ secrets.SSH_KEY }}

      - name: Create tmp directory
        id: create-tmp-dir
        run: |
          tmp_dir=$(ssh ${{ secrets.USER }}@${{ secrets.HOST }} -i ${{ steps.ssh.outputs.private-key-path }} 'mktemp -d')
          echo "Created temporary directory: $tmp_dir"
          echo "tmp_dir=$tmp_dir" >> $GITHUB_OUTPUT
      
      - name: Copy repo to ${{ matrix.deployment-site }}
        run: |
          rsync -r -v -e 'ssh -i ${{ steps.ssh.outputs.private-key-path }}' --exclude={'.git','*_cache'} \
            ${{ github.workspace }} \
            ${{ secrets.USER }}@${{ secrets.HOST_DATA }}:${{ steps.create-tmp-dir.outputs.tmp_dir }}
          echo "Repository at ${{ github.sha }} copied to ${{ steps.create-tmp-dir.outputs.tmp_dir }}/${{ github.event.repository.name }}"

      - name: Run tests on ${{ matrix.deployment-site }}
        run: |
          ssh ${{ secrets.USER }}@${{ secrets.HOST }} -i ${{ steps.ssh.outputs.private-key-path }} /bin/bash <<'EOT'
          set -e
          tmp_dir='${{ steps.create-tmp-dir.outputs.tmp_dir }}'
          chmod -R g+r,g+x "$tmp_dir"
          export MAMBA_ROOT_PREFIX="$tmp_dir"
          env_prefix=${tmp_dir}/environment_${{github.sha}}
          env_file=${tmp_dir}/${{ github.event.repository.name }}/.conda/env_dev.yml
          cleanup() {
            # Remove micromamba environment whenever the script exits
            ${{ vars.MICROMAMBA_EXE }} env remove --prefix $env_prefix --yes &> /dev/null
            rm -rf "$tmp_dir"
            echo "Micromamba environment and temporary directory removed."
          }
          trap cleanup EXIT
          # Create micromamba environment
          echo "Creating micromamba environment"
          echo "  Micromamba executable: ${{ vars.MICROMAMBA_EXE }}"
          echo "  Environment file: $env_file"
          ${{ vars.MICROMAMBA_EXE }} create --prefix $env_prefix --file $env_file --yes
          # Install package as development
          cmd="${{ vars.MICROMAMBA_EXE }} run --prefix $env_prefix pip install --no-deps --no-build-isolation ${tmp_dir}/${{ github.event.repository.name }}"
          echo "Installing '${{ github.event.repository.name }}'"
          echo "  Command: $cmd"
          eval "$cmd"
          # Run tests (using 4 workers in parallel)
          cmd="${{ vars.MICROMAMBA_EXE }} run --prefix $env_prefix pytest -n 4 ${tmp_dir}/${{ github.event.repository.name }}"
          echo "Running tests"
          echo "  Command: $cmd"
          eval "$cmd"
          echo "All tests passed!"
          EOT

  # Dispatch the access-ram-condaenv repo (within the same GitHub organization) to deploy the development conda environment
  dispatch-access-ram-condaenv:
    name: Dispatch the ${{ github.repository_owner }}/access-ram-condaenv repo
    runs-on: ubuntu-latest
    if : ${{ always() && github.event_name == 'pull_request' && needs.verify-conda-build.result != 'failure' }}
    needs: [verify-conda-build, testing]
    steps:
    - name: Dispatch repo
      uses: peter-evans/repository-dispatch@ff45666b9427631e3450c54a1bcbee4d9ff4d7c0 # v3.0.0
      with:
        token: ${{ secrets.REPO_CONTENT_WRITE_TOKEN }}
        repository: ${{ github.repository_owner }}/access-ram-condaenv
        event-type: prerelease
        client-payload: |-
          {
            "token": "${{secrets.REPO_DISPATCH_VERIFICATION_TOKEN}}"
          }